# Generated by Django 4.2.11 on 2024-06-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
