# Generated by Django 4.2.11 on 2024-06-08 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_remove_comment_post_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post',
        ),
    ]
